apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod
    image: 416609528037.dkr.ecr.us-west-1.amazonaws.com/project-pactum:0.1.0-167
    command: ["/bin/sleep", "999999"]
