apiVersion: v1
kind: PersistentVolume
metadata:
  name: gpt2-data
spec:
  capacity: 
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /scratch/gpt2-data
