apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpt2-data
  namespace: elastic-job
spec:
  resources:
    requests:
      storage: 40Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
