apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-a-claim
  namespace: elastic-job
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
